auto: true

markdown: kramdown
kramdown:
    input: GFM
rouge: true
permalink: /:title

title: 猿媛茶馆
url: http://frl1994.github.io/
feed: /atom.xml
author_info: <a href="http://frl1994.github.io/">WalterFRL</a>
